FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/base/gdc-c9s:20231009

COPY *.repo /etc/yum.repos.d/

RUN dnf -y install		\
    gdc-common 			\
    gdc-common-t-unit		\
    gdc-perl-GDC-Bundle-ResBase.noarch \
    gdc-perl-GDC-Bundle-ResBase-t-unit.noarch \
    && dnf clean all		\
    && true

COPY run-tests.sh /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/run-tests.sh" ]
