FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/base/gdc-c9s:20231009

COPY *.repo /etc/yum.repos.d/

RUN dnf -y install			\
    vertica-server			\
    which				\
    iproute				\
    procps-ng				\
    gdc-vertica-udx-gdccsvparser	\
    systemd 				\
    && dnf clean all			\
    && true

RUN /opt/vertica/sbin/install_vertica --license CE --accept-eula --hosts localhost --dba-user-password-disabled --failure-threshold NONE --no-system-configuration --point-to-point --ignore-aws-instance-type --ignore-install-config --no-ssh-key-install --dba-user vertica --dba-group vertica

COPY *.service /usr/lib/systemd/system/
COPY *.sql /opt/
COPY smollcfg.sh /opt/

RUN chmod +x /opt/smollcfg.sh
RUN systemctl enable vertica-init.service vertica.service vertica-finalize.service

EXPOSE 5433

CMD [ "/usr/sbin/init" ]
