FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/base/gdc-c9s:20231009

COPY *.repo /etc/yum.repos.d/

RUN dnf -y install	\
    gdc-common 		\
    gdc-common-t-unit	\
    mariadb		\
    && dnf clean all	\
    && true

COPY run-tests.sh /usr/local/bin/

COPY tests/* /opt/quality/test/unit/gdc-metadata-apps/
COPY modules/* /opt/common/lib/GDC/

ENV GDCTEST_MARIADB_HOST mariadb
ENV GDCTEST_MYSQL_HOST mariadb

ENTRYPOINT [ "/usr/local/bin/run-tests.sh" ]
