FROM 020413372491.dkr.ecr.us-east-1.amazonaws.com/base/gdc-c9s:20231009

RUN dnf -y install postgresql15-server gdc-postgresql15 systemd && dnf clean all

COPY *.service /usr/lib/systemd/system/
COPY *.sql /opt/

RUN systemctl enable postgresql-init.service postgresql-15.service postgresql-finalize.service

EXPOSE 5432

#RUN mkdir /tmp/mddwh_pg_export_test && chmod 2777 /tmp/mddwh_pg_export_test

CMD [ "/usr/sbin/init" ]
