CREATE USER test CREATEDB ENCRYPTED PASSWORD 'testpass';
\c template1;

GRANT ALL ON SCHEMA public TO test;

CREATE EXTENSION IF NOT EXISTS plpgsql;
CREATE EXTENSION IF NOT EXISTS file_fdw;
CREATE EXTENSION IF NOT EXISTS gdc_postgresql;
CREATE EXTENSION IF NOT EXISTS last_access;
CREATE EXTENSION IF NOT EXISTS quantile;

CREATE DATABASE testdb_pg01;
CREATE DATABASE testdb_pg02;
CREATE DATABASE testdb_pg03;
CREATE DATABASE testdb_pg04;
GRANT ALL ON DATABASE testdb_pg01 TO test;
GRANT ALL ON DATABASE testdb_pg02 TO test;
GRANT ALL ON DATABASE testdb_pg03 TO test;
GRANT ALL ON DATABASE testdb_pg04 TO test;
